apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inflightoperations
  name: inflightoperations-operation-admin-role
rules:
- apiGroups:
  - ifo-operator.org
  resources:
  - operations
  verbs:
  - '*'
- apiGroups:
  - ifo-operator.org
  resources:
  - operations/status
  verbs:
  - get
