apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inflightoperations
  name: inflightoperations-operation-editor-role
rules:
- apiGroups:
  - ifo-operator.org
  resources:
  - operations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ifo-operator.org
  resources:
  - operations/status
  verbs:
  - get
