# This rule is not used by the project inflightoperations itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ifo.kubevirt.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: inflightoperations
    app.kubernetes.io/managed-by: kustomize
  name: operation-viewer-role
rules:
- apiGroups:
  - ifo.kubevirt.io
  resources:
  - operations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ifo.kubevirt.io
  resources:
  - operations/status
  verbs:
  - get
