---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ifo.kubevirt.io
  resources:
  - inflightoperations
  - operationrulesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ifo.kubevirt.io
  resources:
  - inflightoperations/finalizers
  - operationrulesets/finalizers
  verbs:
  - update
- apiGroups:
  - ifo.kubevirt.io
  resources:
  - inflightoperations/status
  - operationrulesets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cdi.kubevirt.io
  - kubevirt.io
  - operators.coreos.com
  - "apps"
  verbs:
    - get
    - list
    - watch
  resources:
    - "*"