---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ifo-operator.org
  resources:
  - inflightoperations
  - operationrulesets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ifo-operator.org
  resources:
  - inflightoperations/finalizers
  - operationrulesets/finalizers
  verbs:
  - update
- apiGroups:
  - ifo-operator.org
  resources:
  - inflightoperations/status
  - operationrulesets/status
  verbs:
  - get
  - patch
  - update
