---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watch-role
rules:
  - apiGroups:
      - apps
      - kubevirt.io
      - cdi.kubevirt.io
      - hco.kubevirt.io
      - operators.coreos.com
    verbs:
      - get
      - list
      - watch
    resources:
      - "*"