---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watch-role
rules:
  - apiGroups:
      - ""
      - apps
      - kubevirt.io
      - cdi.kubevirt.io
      - hco.kubevirt.io
      - snapshot.kubevirt.io
      - clone.kubevirt.io
      - export.kubevirt.io
      - networkaddonsoperator.network.kubevirt.io
      - ssp.kubevirt.io
      - hostpathprovisioner.kubevirt.io
      - aaq.kubevirt.io
      - operators.coreos.com
      - machine.openshift.io
      - machineconfiguration.openshift.io
      - config.openshift.io
    verbs:
      - get
      - list
      - watch
    resources:
      - "*"