apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ifo-catalog
  namespace: openshift-marketplace
spec:
  displayName: IFO Catalog
  image: quay.io/slucidi/ifo-controller-index:99.0.0
  publisher: Sam Lucidi
  sourceType: grpc
