apiVersion: ifo-operator.org/v1alpha1
kind: OperationRuleSet
metadata:
  labels:
    app.kubernetes.io/name: inflightoperations
    app.kubernetes.io/managed-by: kustomize
  name: operationruleset-sample
spec:
  # TODO(user): Add fields here
