# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/ifo.kubevirt.io_inflightoperations.yaml
- bases/ifo.kubevirt.io_operationrulesets.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
  - path: patches/selectable-fields.json
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: inflightoperations.ifo.kubevirt.io
# +kubebuilder:scaffold:crdkustomizewebhookpatch
