apiVersion: ifo.kubevirt.io/v1alpha1
kind: OperationRuleSet
metadata:
  name: pvc-rules
spec:
  target:
    group: ""
    version: v1
    resource: persistentvolumeclaims
  rules:
    - operation: Pending
      expression: |
        has(object.status) && has(object.status.phase) && object.status.phase == "Pending"

    - operation: Lost
      expression: |
        has(object.status) && has(object.status.phase) && object.status.phase == "Lost"

    - operation: Resizing
      expression: |
        has(object.status) &&
        has(object.status.conditions) &&
        object.status.conditions.exists(c, c.type == "Resizing" && c.status == "True")

    - operation: FilesystemResizePending
      expression: |
        has(object.status) &&
        has(object.status.conditions) &&
        object.status.conditions.exists(c, c.type == "FileSystemResizePending" && c.status == "True")
